### PR TITLE
Add tappable to image

### PR DESCRIPTION
**Pull request by YonKuma**
Add the tappable class so that iOS gesture handling doesn't eat the taps to zoom and dismiss the picture.

### CODE REVIEW

**Comment by YonKuma** [comment]
Yes, I've been using it. When the image is clicked, it comes up bigger with a dark gray border that fills most of the screen. When the dark gray border is clicked, the zoomed image is hidden and the card returns to normal.

**Comment by bee-san** [comment]
You can test this on desktop by using inspect element -> toggle device bar -> dimensions -> iphone

This emulates the iphone touch event in the browser if I recall :)

**Comment by YonKuma** [comment]
@bee-san That's cool advice, I'll definitely use it in the future. I don't think it allows you to test for this issue though, which is that the iOS gesture regions override the ability to tap on elements that haven't been whitelisted.

**Comment by YonKuma** [comment]
Updated initial summary comment to be more clear about the issue that this PR fixes.

**Comment by bewizible** [comment]
@donkuri I think we can safely merge this PR with Lapis, are you fine with that?

**Comment by bewizible** [comment]
Ok, I think we can call this done now. @YonKuma ありがとうね！

**Pull request merged**
